# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PMMP
title-bold: PocketMine
title-normal: MP
email: youremailaddress@gmail.com
description: Server software for MineCraft Pocket Edition written in PHP
baseurl: ""
url: "https://pmmp.github.io"
author: 
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Plugins
gems:
  - jekyll-sitemap
  - jemoji

# Homepage tiles
#tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url: 
slack_url: 
twitter_url:

# Build settings
markdown: kramdown
